# Generated by Django 3.1.2 on 2020-10-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#ff0000', 'red'), ('#0707fc', 'blue'), ('#fbff01', 'yellow')], default='#ff0000', max_length=10),
        ),
    ]
